version: '3'

services:
  server:
    build:
      context: .
      dockerfile: dockerfile.server
    ports:
      - "5000:5000" # Add the ip address here, i.e '10.10.10.10:5000:5000'
    environment:
      - SERVER_HOST=0.0.0.0 # Not required to change
      - SERVER_PORT=5000 # Dot not change
    volumes:
      - ./server:/server
    restart: unless-stopped

  client:
    build:
      context: .
      dockerfile: dockerfile.client
    environment:
      - SERVER_HOST=server #Ip or Hostname of the server
      - SERVER_PORT=5000 # Change according to the external port of the server
      - KEEPALIVE_INTERVAL=0.25
    volumes:
      - ./client:/client
    restart: unless-stopped
